# Generated by Django 3.1 on 2020-08-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_receita', '0003_receita_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='ativa',
            field=models.BooleanField(default=False),
        ),
    ]
